### ISSUE TITLE
Accessing CommandTimeout property 

### ISSUE THREAD

**Issue by KamyarP** [maxtoroq/DbExtensions#54] opened 2017-07-02 12:40 UTC
Many thanks for sharing your excellent work.
I'd like to be able to change CommandTimeout property. I know CreateCommand lets me have control over the created command. But then I'll lose the dynamic goodness in the SqlSet. Here's a sample of what I'm trying to do:

var query = new SqlBuilder().SELECT("*").FROM("MyTable");
var db = new Database("MyConnectionString", "System.Data.SqlClient");
var data = db.From(query).Skip(start).Take(length);
foreach (dynamic item in data.ToList())
{
...
}

**Comment by maxtoroq** [comment] 2017-07-03 00:31
Duplicate of #52

**Closed** 2017-07-23 22:24 UTC
Labels: duplicate
